services:
  postgres:
    image: postgres:15
    environment:
      POSTGRES_USER: triviafutbol
      POSTGRES_PASSWORD: triviafutbol
      POSTGRES_DB: triviafutbol_dev
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data

volumes:
  postgres_data: