name: Deploy a Render

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout código
        uses: actions/checkout@v4

      - name: Ejecutar Deploy en Render
        run: |
          curl -X POST ${{ secrets.RENDER_DEPLOY_HOOK }}

      - name: Notificar deploy exitoso
        run: echo "✅ La aplicación se ha actualizado en Render con éxito"